apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-simple-app-deployment
  labels:
    app: django-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: django-simple-app
        image: django-simple-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000