version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/simple_django_web/simpleapp/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/simple_django_web/simpleapp/
    ports:
      - "8000:8000"
    env_file:
      - .env