version: '3'
services:
  nginx:
#    image: nginx:latest
    build:
      context: .
      dockerfile: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/simple_django_web
#      - ./nginx:/etc/nginx/conf.d
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - .:/simple_django_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - .env